org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Stack=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
kotlin.code.style=official
android.aapt2FromMaven=false
android.aapt2.override=/data/data/com.termux/files/usr/bin/aapt2
